"use strict";

GSUI.setTemplate( "popup-settings", () => (
	GSUI.createElement( "div", { id: "settingsPopupContent", class: "popup" },
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Audio" ),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Feedback sample rate" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "select", { id: "settingsPopupSampleRate", name: "sampleRate" },
						GSUI.createElement( "option", { value: 8000 }, "8 kHz" ),
						GSUI.createElement( "option", { value: 11025 }, "11.025 kHz" ),
						GSUI.createElement( "option", { value: 12000 }, "12 kHz" ),
						GSUI.createElement( "option", { value: 22050 }, "22.05 kHz" ),
						GSUI.createElement( "option", { value: 24000 }, "24 kHz" ),
						GSUI.createElement( "option", { value: 44100 }, "44.1 kHz" ),
						GSUI.createElement( "option", { value: 48000, style: "font-weight:bold" }, "48 kHz" ),
						GSUI.createElement( "option", { value: 88200 }, "88.2 kHz" ),
						GSUI.createElement( "option", { value: 96000 }, "96 kHz" ),
					),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "UI refresh rate" ),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Auto" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "label", null,
						GSUI.createElement( "input", { id: "settingsUIRateModeAuto", name: "UIRateMode", type: "radio", value: "auto" } ),
						GSUI.createElement( "span", { class: "settingsPopupNumber settingsPopupFps" }, 60 ),
					),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Manual" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "label", null,
						GSUI.createElement( "input", { id: "settingsUIRateModeManual", name: "UIRateMode", type: "radio", value: "manual" } ),
						GSUI.createElement( "span", { id: "settingsUIRateManualFps", class: "settingsPopupNumber settingsPopupFps" } ),
					),
					GSUI.createElement( "input", { id: "settingsUIRateManual", name: "UIRateManual", type: "range", step: 1, min: 5, max: 40 } ),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Windows" ),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Move/resize mode" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "label", null,
						GSUI.createElement( "input", { id: "settingsWindowsMode", name: "windowsDirectMode", type: "checkbox" } ),
						GSUI.createElement( "span", null, "direct" ),
					),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Timeline" ),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Numbering measures starting at" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "select", { id: "settingsTimelineNumbering", name: "timelineNumbering" },
						GSUI.createElement( "option", { value: 0 }, 0 ),
						GSUI.createElement( "option", { value: 1 }, 1 ),
					),
				),
			),
		),
	)
) );
