"use strict";

GSUI.setTemplate( "popup-shortcuts", () => (
	GSUI.createElement( "div", { id: "shortcutsPopupContent", class: "popup" },
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Global shortcuts" ),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Save the current composition" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "S" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Open a composition" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "O" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Open a new composition" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "N" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Play / pause the selected grid" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Space" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Undo the previous action" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Z" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Redo the next action" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Shift" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Z" ),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Grids shortcuts" ),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Select all the blocks of the focused grid" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "A" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Deselect all the blocks of the focused grid" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "D" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Duplicate (copy/paste) the selected blocks" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / Alt" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" }, "B" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Delete all the selected blocks of the focused grid" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Delete" ),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Move vertically inside the grids" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" },
						"Scroll ",
						GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" }, "Move horizontally inside the grids" ),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Shift" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" },
						"Scroll ",
						GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
			GSUI.createElement( "div", { class: "param" },
				GSUI.createElement( "div", { class: "param-title" },
					"Zoom-in / zoom-out", GSUI.createElement( "br" ),
					"Zoom X by scrolling above the grid", GSUI.createElement( "br" ),
					"Zoom Y by scrolling above the keys", GSUI.createElement( "br" ),
				),
				GSUI.createElement( "div", { class: "param-values" },
					GSUI.createElement( "kbd", { class: "shortcuts" }, "Ctrl / ⌘" ),
					GSUI.createElement( "i", { class: "shortcuts-sep gsuiIcon", "data-icon": "plus" } ),
					GSUI.createElement( "kbd", { class: "shortcuts" },
						"Scroll ",
						GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "arrows-v" } ),
					),
				),
			),
		),
	)
) );
